### ISSUE TITLE
Model Testing

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos93h2#2]
Hi! 
This model is ready for testing!

**Comment by paulinebanye** [comment]
Hi @GemmaTuron 
### MODEL TEST FOR EOS93H2

## CLI
- [x] Model eos93h2 fetched, served and predicted successfully on the CLI.
- [X] Model was tested using a list of smiles and a single smile string
[eos93h2_fetch.log](https
[eos93h2_predict.csv](https://github.com/ersilia-os/eos93h2/files/10752252/eos93h2_predict.csv)
://github.com/ersilia-os/eos93h2/files/10752250/eos93h2_fetch.log)
[eos93h2_list_predict.csv](https://github.com/ersilia-os/eos93h2/files/10752253/eos93h2_list_predict.csv)


## COLAB
- [x]  Model eos93h2 fetched, served and predicted successfully on colab
[eos93h2_output.csv](https://github.com/ersilia-os/eos93h2/files/10752287/eos93h2_output.csv)
https://colab.research.google.com/drive/1ryBKyfz2hZAWPnq9kdgUaSkeiArONTgh?usp=sharing

**Comment by GemmaTuron** [comment]
@karthikjetty 
This task was due by 20th Feb, please provide update

**Comment by karthikjetty** [comment]
I get the same issue with this model as with testing eos74bo. I will try the solution on both of the models to see if it works.
